config/routes.rb
Rails.application.routes.draw do
  get 'session/new'
  get 'users/new'
  root :to => 'pages#home'

  # resources :users, :only => [:new, :create]
  resources :users do
    member do
      get :following, :followers
    end
  end

  resources :sessions,      only: [:new, :create, :destroy]
  resources :tweets
  resources :relationships, only: [:create, :destroy]

  get '/login' => 'session#new'
  post '/login' => 'session#create'
  delete '/login' => 'session#destroy'

  resources :tweets do
    resources :comments
  end
  
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :tweet, :optional => true
  belongs_to :user, :optional => true
end

app/models/relationship.rb
class Relationship < ApplicationRecord
  belongs_to :follower, class_name: "User"
  belongs_to :followed, class_name: "User"
  validates :follower_id, presence: true
  validates :followed_id, presence: true
end

app/models/tweet.rb
class Tweet < ApplicationRecord
  belongs_to :user, :optional => true

  has_many :comments, :dependent => :destroy

  # validates :title, presence: true,
  #                 length: { minimum: 5 }

  # delegate :name, to: :user
end

app/models/user.rb
class User < ActiveRecord::Base
  has_secure_password

  validates :email, :presence => true, :uniqueness => true

  has_many :tweets, dependent: :destroy
  has_many :comments

  has_many :relationships, foreign_key: "follower_id", dependent: :destroy
  has_many :followed_users, through: :relationships, source: :followed

  has_many :reverse_relationships, foreign_key: "followed_id",
                                   class_name:  "Relationship",
                                   dependent:   :destroy
  has_many :followers, through: :reverse_relationships, source: :follower

  def feed
    Tweet.from_users_followed_by(self)
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :fetch_user

  private
  def fetch_user
    @current_user = User.find_by :id => session[:user_id] if session[:user_id].present?
    session[:user_id] = nil unless @current_user.present?
  end

  def check_for_login
    redirect_to login_path unless @current_user.present?
  end

  def check_for_admin
    redirect_to root_path unless @current_user.present? && @current_user.admin?
  end

end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController

  def create
      @tweet = Tweet.find(params[:tweet_id])
      @comment = @tweet.comments.create(comment_params)
      @current_user.comments << @comment
      redirect_to tweets_path(@tweet)
  end

  def destroy
    @tweet = Tweet.find(params[:tweet_id])
    @comment = @tweet.comments.find(params[:id])
    @comment.destroy
    redirect_to tweets_path(@tweet)
  end

  private
    def comment_params
      params.require(:comment).permit(:commenter, :body)
    end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
    @tweets = Tweet.all
  end
end

app/controllers/relationships_controller.rb
class RelationshipsController < ApplicationController

  def create
    @user = User.find(params[:relationship][:followed_id])
    @current_user.followed_users << @user
    redirect_to @user
  end

  def destroy
    @user = Relationship.find(params[:id]).followed
    @current_user.followed_users.delete @user
    redirect_to @user
  end
end

app/controllers/session_controller.rb
class SessionController < ApplicationController

  def new
  end

  def create
    user = User.find_by :email => params[:email]
    if user.present? && user.authenticate(params[:password])
      session[:user_id] = user.id
      redirect_to tweets_path
    else
      flash[:error] = "Invalid username or password"
      redirect_to login_path
    end
  end

  def destroy
    session[:user_id] = nil
    redirect_to login_path
  end
end

app/controllers/tweets_controller.rb
class TweetsController < ApplicationController
  before_action :check_for_login

  def index
    @tweets = Tweet.order "created_at desc"
  end

  def show
    @tweet = Tweet.find params[:id]
  end

  def new
    @tweet = Tweet.new
  end

  def create
    tweet = Tweet.create tweet_params
    @current_user.tweets << tweet
    if params[:file].present?
      req = Cloudinary::Uploader.upload(params[:file])
      tweet.image = req["public_id"]
      tweet.save
    end
    redirect_to tweets_path
  end

  def edit
    @tweet = Tweet.find params[:id]
  end

  def update
    tweet = Tweet.find params[:id]
    if params[:file].present?
      req = Cloudinary::Uploader.upload(params[:file])
      tweet.image = req["public_id"]
    end
    tweet.update tweet_params
    tweet.save
    redirect_to @current_user
  end

  def destroy
    tweet = Tweet.find params[:id]
    tweet.destroy
    redirect_to @current_user
  end

  private
  def tweet_params
     params.require(:tweet).permit(:user_id, :content, :image)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
before_action :check_for_admin, :only => [:index]

  def index
    @users = User.all
  end

  def show
    @user = User.find params[:id]
  end

  def new
    @user = User.new
  end

  def create
    @user = User.new user_params
      if @user.save
      session[:user_id] = @user.id
      redirect_to tweets_path
        else
          render :new
          if params[:file].present?
            req = Cloudinary::Uploader.upload(params[:file])
            user.image = req["public_id"]
            user.save
        end
      end
  end

  def edit
    @user = User.find params[:id]
  end

  def update
    user = User.find params[:id]
    if params[:file].present?
      req = Cloudinary::Uploader.upload(params[:file])
      user.image = req["public_id"]
    end
    user.update user_params
    user.save
    redirect_to user
  end

  def following
    @title = "Following"
    @user = User.find(params[:id])
    @users = @user.followed_users
    render :following
  end

  def followers
    @title = "Followers"
    @user = User.find(params[:id])
    @users = @user.followers
    render :followers
  end

  def following?(other_user)
    relationships.find_by(followed_id: other_user.id)
  end

  def follow!(other_user)
    relationships.create!(followed_id: other_user.id)
  end

  def unfollow!(other_user)
    relationships.find_by(followed_id: other_user.id).destroy
  end

  private
  def user_params
    params.require(:user).permit(:name, :email, :password, :password_confirmation, :follower_id, :followed_id, :bio, :image, :title)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/session_helper.rb
module SessionHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/comments/_comment.html.erb
<p>
  <% if comment.user.image.present? %>
    <%= cl_image_tag(comment.user.image, :class => 'icon') %>
  <% else %>
    <%= image_tag 'empty-profile-picture.png', :class => 'icon' %>
  <% end %>
  <strong><%= comment.user.name %>:</strong> <%= comment.body %>
</p>

<p>
  <% if @tweet.user.id == @current_user.id || comment.user_id == @current_user.id %>
    <%= link_to "#{@current_user.name} Delete Comment?", [comment.tweet, comment],
                 method: :delete,
                 data: { confirm: 'Are you sure?' } %>
  <% end  %>
</p>

app/views/comments/_form.html.erb
<%= form_with(model: [ @tweet, @tweet.comments.build], local: true) do |f| %>

    <%= f.label :Comment %>
    <%= f.text_area :body %>

    <%= f.submit %>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Project1</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= cloudinary_js_config %>
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
  </head>

  <body>
    <div class="navbar">
      <% if @current_user.present? && @current_user.admin %>
        <%= link_to "Social Feed", tweets_path %>
        <%= link_to "Add Post", new_tweet_path %>
        <%= link_to "Admin Page", users_path %>
      <% elsif @current_user.present? %>
        <%= link_to "Social Feed", tweets_path %>
        <%= link_to "Add Post", new_tweet_path %>
        <% else %>
          <%= link_to "Home", root_path %>
          <%= link_to 'Sign Up', new_user_path %>
          <%= link_to "Login", login_path %>
      <% end %>

      <div class="dropdown">
        <% if @current_user.present? %>
          <button class="dropbtn">
            <div class="row">
              <div class="row right-align icon-position">
                <% if @current_user.image %>
                  <%= cl_image_tag(@current_user.image, :class => 'icon') %>
                <% else %>
                  <%= image_tag 'empty-profile-picture.png', :class => 'icon' %>
                <% end %>
              </div>
              <div class="row right-align">
                <%= @current_user.name %>
              </div>
            </div>
          </button>
        <% end %>
        <div class="dropdown-content">
          <% if @current_user.present? %>
            <%= link_to "Profile Page", user_path(@current_user.id) %>
            <%= link_to "Update Profile", edit_user_path(@current_user) %>
            <%= link_to "Logout #{ @current_user[:name]}", login_path, :method => 'delete' %>
          <% end %>
        </div>
      </div>
    </div>
    <div class="container">
      <%= yield %>
    </div>
  </body>
</html>

app/views/pages/home.html.erb
<% if @current_user.present? %>
<div>
  <h2>Your social networking platform</h2>
    <main>
      <h4>Lovely to see you here <%= @current_user.name %></h4>
      <h4>I know you are checking my url/paths are locked!</h4>
      <%= image_tag 'socialmedia', :class => 'home-image' %>
    </main>
</div>

<% else %>
  <div>
    <h1>Social Networking<h1>

    <main>
      <p>This is a free social networking platform allowing registered members to post pictures and text throughout the day.
      <p>As a member you can post content as well as comment on other members posts.</p>
      <p>You have full control to update your profile page, adding a profile picture, biography and even add a title.</p>
      <p>Follow other users and find out more about them by looking at their profile pages.</p>

    </main>
    <aside>
      <h4><%= link_to 'Login', login_path%> or <%= link_to 'Create an Account', new_user_path %></h4>
    </aside>

  </div>
<% end %>

app/views/session/new.html.erb
<h1>Sign In</h1>

<% if flash[:error].present? %>
  <h2><%= flash[:error] %></h2>
<% end %>

<%= form_tag login_path do %>
  <div class="form-group">
    <%= label_tag :email %>
    <%= email_field_tag :email, nil, :class => 'form-control' %>
  </div>

  <div class="form-group">
    <%= label_tag :password %>
    <%= password_field_tag :password, nil, :class => 'form-control' %>
  </div>

  <%= submit_tag "Sign In" %>
<% end %>

app/views/shared/_stats.html.erb
<% @user ||= current_user %>

<div class="stats">
  <a href="<%= following_user_path(@user) %>">
    <strong id="following" class="stat">
      <%= @user.followed_users.count %>
    </strong>
    following
  </a>
  <a href="<%= followers_user_path(@user) %>">
    <strong id="followers" class="stat">
      <%= @user.followers.count %>
    </strong>
    followers
  </a>
</div>

app/views/tweets/_form.html.erb
<%= form_for(@tweet, :html => {:multipart => true}) do |f| %>
  <div class="form-group">
    <%= f.label :content %>
    <%= f.text_field :content, :class => 'form-control'  %>
  </div>

  <div class="form-group">
    <%= f.label :image %>
    <%= f.cl_image_upload :image, :class => 'form-control' %>
  </div>

  <%= f.submit %>
<% end %>

app/views/tweets/_tweets.html.erb
<% @tweets.each do |tweet|  %>
  <ul class="tweet-container">
    <li><strong>Post by:
      <% if tweet.user.image.present? %>
        <%= cl_image_tag(tweet.user.image, :class => 'icon') %>
      <% else %>
        <%= image_tag 'empty-profile-picture.png', :class => 'icon' %>
      <% end %>

      <%= link_to "#{tweet.user.name}", user_path(tweet.user.id)  %></strong> |
      <%= tweet.created_at.strftime '%e %b %Y' %>
    </li>

    <p class="link-style"><%= link_to "#{tweet.content}", tweet_path(tweet.id) %></p>
    <li><% if tweet.image.present? %>
          <%= cl_image_tag(tweet.image, :class => 'tweet-image') %>
        <% end %></li>

<%# Display if there are comments for the tweet, if so place comment box within the drop down at the end %>
    <% if tweet.comments.present? %>
      <div class="dropdown">
        <div class="comments-btn">Read and Add Post Comments
          <i class="fa fa-caret-down"></i>
        </div>
        <div class="dropdown-content tweet-comments">

          <% tweet.comments.each do |comment| %>
            <p>
              <% if comment.user.image.present? %>
                <%= cl_image_tag(comment.user.image, :class => 'icon') %>
              <% else %>
                <%= image_tag 'empty-profile-picture.png', :class => 'icon' %>
              <% end %>

              <%= comment.created_at.strftime '%l:%M%P, %e %b' %> |
              <strong><%= comment.user.name %></strong> |
              <%= comment.body %>
              </p>
              <p class="delete-comment">
              <% if comment.user_id == @current_user.id || @current_user.admin %>
                <%= link_to "#{@current_user.name} Delete Comment?", [comment.tweet, comment],
                             method: :delete,
                             data: { confirm: 'Are you sure?' } %>
              <% end  %>
            </p>

          <% end %>
          <%= form_with(model: [ tweet, tweet.comments.build], local: true) do |f| %>
            <p>
              <%= f.text_area :body, placeholder: 'Add your comment here!'%>
              <%= f.submit %>
            </p>
          <% end %>
          </div>

<%# ## Display comment box on dom if there are not already comments   %>
    <% else %>
      <%= form_with(model: [ tweet, tweet.comments.build], local: true) do |f| %>
        <p>
          <%= f.text_area :body, placeholder: 'Add your comment here!'%>
          <%= f.submit %>
        </p>
      <% end %>
    <% end %>
  </ul>
<% end %>

app/views/tweets/edit.html.erb
<h2>Edit Post</h2>

<%= render :partial => 'form' %>

app/views/tweets/index.html.erb
<h2>Social Feed</h2>

<%= render 'tweets' %>

app/views/tweets/new.html.erb
<h2>Add New Post</h2>

<%= render :partial => 'form' %>

app/views/tweets/show.html.erb
<div class="space-between">
  <h2 class="row">Post</h2>
  <div class="row right-align">
    <%= link_to 'Back', tweets_path %>
  </div>
</div>

<ul class="tweet-container">
  <li><strong>Post by:</strong>
    <% if @tweet.user.image.present? %>
      <%= cl_image_tag(@tweet.user.image, :width=>32, :height=>32, :gravity=>"face", :radius=>"max", :crop=>"fill", :background=>"#f2f2f2") %>
        <% else %>
          <%= image_tag 'empty-profile-picture.png', :class => 'icon' %>
    <% end %>

    <strong><%= link_to "#{@tweet.user.name}", user_path(@tweet.user.id) %></strong> |
    <%= @tweet.created_at.strftime '%e %b %Y' %></li>
    <p class="link-style"><%= @tweet.content %></p>
        <% if @tweet.image.present? %>
          <li><%= cl_image_tag(@tweet.image, :height => 144) %></li>
        <% end %>

    <%= render @tweet.comments %>
    <%= render 'comments/form' %>
</ul>

app/views/users/_follow.html.erb
<%= form_for(@current_user.relationships.build(followed_id: @user.id)) do |f| %>
    <div><%= f.hidden_field :followed_id %></div>
  <%= f.submit "Follow", class: "btn-follow" %>
<% end %>

app/views/users/_follow_form.html.erb
<% if @current_user.present? %>
  <% if @current_user.followed_users.include? @user %>
    <%= render 'unfollow' %>
  <% else %>
    <%= render 'follow' %>
  <% end %>
<% end %>

app/views/users/_form.html.erb
<%= form_for @user do |f| %>
  <div class="form-group">
    <%= f.label "user name"%>
    <%= f.text_field :name %>
  </div>

  <div class="form-group">
    <%= f.label :email %>
    <%= f.email_field :email%>
  </div>

  <div class="form-group">
    <%= f.label :password %>
    <%= f.password_field :password %>
  </div>

  <div class="form-group">
    <%= f.label :password_confirmation %>
    <%= f.password_field "password_confirmation" %>
  </div>

  <%= f.submit "Create Account" %>

<% end %>

app/views/users/_stats.html.erb
<% @user ||= @current_user %>
<div class="stats">
  <a href="<%= following_user_path(@user) %>">
    <strong id="following" class="stat">
      <%= @user.followed_users.count %>
    </strong>Following</a>

  <a href="<%= followers_user_path(@user) %>">
    <strong id="followers" class="stat">
      <%= @user.followers.count %>
    </strong>Followers </a>
</div>

app/views/users/_tweets.html.erb
<% @user.tweets.each do |tweet|  %>
  <ul class="tweet-container">
    <li><strong>Post by:
      <% if tweet.user.image.present? %>
      <%= cl_image_tag(tweet.user.image, :class => 'icon') %>
        <% else %>
        <%= image_tag 'empty-profile-picture.png', :class => 'icon' %>
      <% end %>
      <%= link_to "#{tweet.user.name}", user_path(tweet.user.id)  %></strong> |
      <%= tweet.created_at.strftime '%A, %B %e, %Y' %>
    </li>

    <p class="link-style"><%= tweet.content %></p>

    <li><% if tweet.image.present? %>
          <%= cl_image_tag(tweet.image, :height=>144) %>
        <% end %>
    </li>

    <% if tweet.user.id == @current_user.id || @current_user.admin %>
    <li><%= link_to "Edit", edit_tweet_path(tweet) %> |
        <%= link_to "Delete", tweet, :method => 'delete', :data => { :confirm => 'Are you sure?'} %></li>
        <% end %>
  </ul>
<% end %>

app/views/users/_unfollow.html.erb
<%= form_for(@current_user.relationships.find_by(followed_id: @user.id),
             html: { method: :delete }) do |f| %>
  <%= f.submit "Unfollow", class: "btn-follow" %>
<% end %>

app/views/users/edit.html.erb
<h1>Edit page</h1>

<%= form_for(@user, :html => {:multipart => true}) do |f| %>
  <div class="form-group">
    <%= f.label "user name"%>
    <%= f.text_field :name %>
  </div>

  <div class="form-group">
    <%= f.label :email %>
    <%= f.email_field :email %>
  </div>

  <div class="form-group">
    <%= f.label :password %>
    <%= f.password_field :password %>
  </div>

  <div class="form-group">
    <%= f.label :password_confirmation %>
    <%= f.password_field "password_confirmation"%>
  </div>

  <div class="form-group">
    <%= f.label :title %>
    <%= f.text_field :title %>
  </div>

  <div class="form-group">
    <%= f.label :bio %>
    <%= f.text_field :bio %>
  </div>

  <div class="form-group">
  <%= f.label :image %>
  <%= f.cl_image_upload :image %>
  </div>

  <%= f.submit "Update Account" %>
<% end %>

app/views/users/followers.html.erb
<h2>Followers page</h2>

<div class="stats">
  <% if @user.followers.present? %>
  <%= "You have #{@user.followers.count} followers: " %>
    <% @user.followers.each do |follower| %>
      <li><%= link_to follower.name, follower %></li>
    <% end %>
    <% else %>
      <%= "You have zero followers." %>
  <% end %>

  </div>

app/views/users/following.html.erb
<h2>Following</h2>

<div class="stats">
  <% if @user.followed_users.present? %>
    <%= "#{@user.name} you are following #{@user.followed_users.count } users: "%>
      <% @user.followed_users.each do |followed| %>
        <li><%= link_to followed.name, followed %></li>
      <% end %>
      <% else %>
        <%= "You are not following anyone." %>
  <% end %>
</div>

app/views/users/index.html.erb
<h1>All Users</h1>

<% @users.each do |user| %>
<ul>

  <li>Name: <%= user.name %><%= cl_image_tag(user.image, :class => 'icon') %></li>
  <li>Email: <%= user.email %></li>
  <li>Title: <%= user.title %></li>
  <li>Bio: <%= user.bio %></li>
  <li>Created: <%= user.created_at %></li>

</ul>
<% end %>

app/views/users/new.html.erb
<h1>Create New Account</h1>

<% if @user.errors.any? %>
  <ol>
    <% @user.errors.full_messages.each do |msg| %>
    <li><%= msg %></li>
    <% end %>
  </ol>
<% end %>

<%= render :partial => 'form' %>

app/views/users/show.html.erb
<div class="space-between">
    <div class="space-between">
      <div class="row icon-position">
        <% if @user.image.present? %>
        <%= cl_image_tag(@user.image, :class => "profile-icon") %>
        <% else %>
          <%= image_tag 'empty-profile-picture.png', :class => 'icon' %>
          <% end %>
      </div>
      <div class="row right-align">
        <h1><%= @user.name %></h1>
      </div>
    </div>

    <div class="row right-align">
        <%= render 'follow_form' if @current_user.present?  %>
    </div>
</div>

<p class="user-title"><strong><%= @user.title %></strong></p>
<p><%= @user.bio %></p>

<br>
<div class="space-between">
  <div class="row">
    <%= render 'stats' %>
  </div>
  <div class="row right-align">
    <%= link_to 'Back', tweets_path %>
  </div>
</div>

<section>
  <%= render 'tweets' %>
</section>

app/views/users/show_follow.html.erb
<%= render :partial => 'stats' %>